name: "AMI Build (Packer)"

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  build-proxy:
    name: Build Proxy AMI
    if: >
      contains(github.event.pull_request.labels.*.name, 'build:proxy') ||
      contains(github.event.pull_request.labels.*.name, 'build:both')
    runs-on: ubuntu-latest
    environment: T4-build

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-packer@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::971778147356:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - name: Build Proxy AMI
        run: |
          cd proxy
          packer init .
          packer build .

  build-ansible:
    name: Build Ansible AMI
    if: >
      contains(github.event.pull_request.labels.*.name, 'build:ansible') ||
      contains(github.event.pull_request.labels.*.name, 'build:both')
    runs-on: ubuntu-latest
    environment: T4-build

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-packer@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::971778147356:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - name: Build Ansible AMI
        run: |
          cd ansible
          packer init .
          packer build .